In [7]:
# Question 0: Make a function that prints out "I Love IS 115/505!" and then call it
def lovePhrase():
  print("I Love IS 115/505!")

lovePhrase()

I Love IS 115/505!

In [10]:
#Background: You are currently staying at Camp Green Lake where every "Camper" is required to dig a 5 foot deep hole daily. Fortunately for you
# the warden, Louise Walker, heard you know some programming and has a slightly less labor intensive job for you. Camp Green Lake knows the depths
# of all their holes but the radius varies, and they need to report exactly how many cubic feet have been moved in the month of May. This
# would take weeks to do by hand but using your coding skills you can do it in a few minutes.


# Question 1: Create a function that will recieve a hole/cylinder's radius as an input and then returns the volume of that cylinder.
# Use this function to show the volume of a cylinder with a radius of 5 ft and then print out the result as a f string that says
# "Area: {area_variable} cubed feet." where the area variable is the value your function returns. Round your answer to the two decimal places.

str_radius = input("Enter the radius of the cylinder/hole: ")
r = float(str_radius)
print('\n')

def volume():
  pi = 3.1415
  H = 5 # H = height this is a given constant
  volume = r**2 * H * pi
  print(f"Area: {volume:.2f} cubed feet.")

volume()


# For the purpose of this question you can use the value of 3.1415 as a constant for pi and 5 is a constant for height.
# Formula for the volume of a cylinder: pi*r^2*H  r = radius H = height

Enter the radius of the cylinder/hole: 5.6


Area: 492.59 cubed feet.

In [18]:
# Question 2: Here we have a list of the holes dug in the month of May.
# Create a loop that will use your volume generating function  and then find the total abount of cubic feet of dirt moved in May. Save that
# value rounded to the second decimal place in a value called total_dirt and then output it.
total_dirt = float()
may_radius_list = [1.29, 0.5, 0.5, 5.6, 0.89, 1.97, 1.04, 7.42, 2.31, 2.0, 4.06, 4.04, 1.2, 2.68, 7.66, 7.23, 3.3, 3.03, 2.48,
               1.54, 1.4, 4.97, 8.45, 7.22, 6.68, 2.88, 5.49, 2.18, 5.76, 7.36, 0.6, 5.71, 7.67, 3.06, 5.33, 1.21, 1.75, 7.53, 6.63,
               5.54, 5.34, 0.76, 8.11, 1.52, 8.03, 5.29, 1.09, 1.25, 4.04, 5.23, 4.83, 1.52, 5.32, 7.34, 4.87, 6.23, 7.73, 5.1, 5.85, 0.78,
               1.02, 7.17, 7.4, 1.83, 6.74, 8.08, 5.46, 5.03, 6.8, 8.48, 4.56, 1.2, 1.11, 5.39, 7.03, 8.42, 5.55, 1.45, 0.73, 8.38, 7.95,
               1.16, 7.22, 7.23, 5.83, 5.85, 4.77, 7.51, 8.12, 6.06, 3.03, 3.06, 3.1, 0.96, 1.35, 0.93, 3.61, 8.08, 7.35, 4.27, 3.84,
               2.45, 8.46, 6.1, 4.87, 3.02, 3.27, 8.1, 3.13, 1.1, 6.65, 3.16, 0.95, 7.74, 0.85, 3.09, 6.27, 5.61, 6.36, 4.75, 4.72, 2.68,
               3.95, 8.07, 4.2, 0.61, 7.78, 6.6, 4.98, 1.06, 6.93, 3.51, 3.91, 6.93, 1.15, 2.47, 6.19, 4.23, 0.9, 4.16, 3.9, 5.2, 7.07,
               4.29, 2.02, 4.79, 1.56, 1.75, 5.57, 2.42, 2.1, 0.71, 8.08, 3.27, 3.51, 2.45, 5.29, 3.89, 7.25, 7.24, 8.21, 2.33, 6.94, 4.9,
               8.27, 7.85, 7.15, 0.57, 3.57, 7.48, 5.28, 5.16, 2.8, 4.64, 8.38, 5.6, 4.19, 0.91, 5.43, 5.25, 7.23, 0.52, 2.02, 6.14, 5.05,
               7.65, 1.58, 6.91, 2.37, 8.08, 0.54, 5.87, 5.71, 5.97, 1.23, 3.06, 8.24, 8.42, 2.4, 5.73, 2.73, 3.32, 3.47, 2.97, 3.14, 3.87,
               3.86, 4.09, 1.23, 3.99, 7.58, 6.65, 6.64, 1.83, 8.44, 1.28, 0.5, 3.97, 7.82, 6.68, 4.33, 1.54, 6.47, 4.81, 6.82, 5.85, 2.25,
               0.73, 1.29, 5.28, 3.49, 0.86, 4.87, 8.34, 3.23, 0.99, 2.84, 3.71, 1.53, 1.03, 6.9, 6.15, 5.49, 7.59, 6.35, 0.61, 2.46, 2.62,
               2.82, 7.79, 2.32, 6.88, 4.51, 3.03, 1.68, 4.53, 6.1, 3.05, 3.48, 5.97, 4.63, 5.4, 8.01, 6.38, 1.01, 4.15, 2.43, 3.13, 2.74,
               1.46, 1.87, 1.18, 6.09, 2.45, 2.32, 4.59, 1.74, 3.49, 8.36, 5.74, 8.13, 1.01, 1.39, 0.76, 5.69, 5.61, 4.82, 2.03, 2.5, 3.22,
               4.9, 5.61, 6.99, 6.5, 2.05, 7.18, 8.13, 0.62, 2.6]


def volume(radius):
  pi = 3.1415
  H = 5 # H = height this is a given constant
  volume = r**2 * H * pi
  return volume

for radius in may_radius_list:
  total_dirt += volume(radius)

total_dirt = round(total_dirt, 2)

print(f"Cubic feet of dirt moved: {total_dirt} Square Feet of Dirt")

Cubic feet of dirt moved: 147283.57 Square Feet of Dirt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [25]:
# Question 3: The warden also wants to be able to pull out the info about holes dug based on specific criteria.
# Using the Pandas library read the Holes.csv into this cell

import pandas as pd

df = pd.read_csv('/content/Holes-Freymiller.csv')

def parameters(dataframe, column_name, filter_value):
  df_filtered = dataframe[dataframe[column_name] == filter_value]
  return df_filtered

filter_Zero = parameters(df, 'Name', 'Zero')

display(filter_Zero)

# Create a function that will recieve 3 parameters: a dataframe & a string representing the column name & a string representing the filter value
# then output a filtered dataframe that only displays info for the name matching the string that was passed in.
# Call this function with the correct parameters to return all holes dug by "Zero" (output the resulting dataframe)

    Unnamed: 0  Name  Radius       Date
2            2  Zero     8.4   5/7/2020
6            6  Zero     9.2   5/8/2020
10          10  Zero     7.1   5/9/2020
14          14  Zero     9.9  5/10/2020
18          18  Zero     3.2  5/11/2020

In [26]:
#Question 4: Finally we want to know the details about all the holes that were dug on May 7 2020. Use the fuction you made in the last
# problem to find only the records where date = "05-07-2020"


import pandas as pd

df = pd.read_csv('/content/Holes-Freymiller.csv')

def parameters(dataframe, column_name, filter_value):
  df_filtered = dataframe[dataframe[column_name] == filter_value]
  return df_filtered

filter_Zero = parameters(df, 'Date', '5/7/2020')

display(filter_Zero)

   Unnamed: 0     Name  Radius      Date
0           0  CaveMan     4.2  5/7/2020
1           1    X Ray     5.1  5/7/2020
2           2     Zero     8.4  5/7/2020
3           3   Armpit     8.0  5/7/2020